### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings

### ISSUE THREAD

**Issue by dmitriz** [SabreDevStudio/sabre-dev-studio-node#17]
Getting this error when running the demo example from https://github.com/SabreDevStudio/sabre-dev-studio-node

```sh

{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zaitsev/tests/sabre/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zaitsev/tests/sabre/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zaitsev/tests/sabre/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{"Themes":[{"Theme":"BEACH","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/BEACH"}]},{"Theme":"CARIBBEAN","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/CARIBBEAN"}]},{"Theme":"DISNEY","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/DISNEY"}]},{"Theme":"GAMBLING","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/GAMBLING"}]},{"Theme":"HISTORIC","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/HISTORIC"}]},{"Theme":"MOUNTAINS","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/MOUNTAINS"}]},{"Theme":"NATIONAL-PARKS","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/NATIONAL-PARKS"}]},{"Theme":"OUTDOORS","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/OUTDOORS"}]},{"Theme":"ROMANTIC","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/ROMANTIC"}]},{"Theme":"SHOPPING","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/SHOPPING"}]},{"Theme":"SKIING","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/SKIING"}]},{"Theme":"THEME-PARK","Links":[{"rel":"destinations","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes/THEME-PARK"}]}],"Links":[{"rel":"self","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes"},{"rel":"linkTemplate","href":"https://api.test.sabre.com/v1/lists/supported/shop/themes"}]}
```

**Comment by captainjackrana** [comment]
This has to do with the dependency on `bunyan` that requires `dtrace-provider`.

https://github.com/trentm/node-bunyan/issues/216
